### ISSUE TITLE
maxFontSize not working

### ISSUE THREAD

**Issue by w-m** [michikono/boxfit#2]
I am not familiar with JavaScript and jQuery, so excuse if I'm missing something, but it seems to me that the maxFontSize option has not actually been implemented.

Adding the following code into the while loop does what I would the option expect to do:

``` javascript
if (settings.maxFont) {
  if (parseInt(inner_span.css("font-size"), 10) >= parseInt(settings.maxFontSize, 10)) {
    break;
  }
}
```

**Comment by michikono** [comment]
I believe this is now resolved. Thank you.
