### ISSUE TITLE
Angular js

### ISSUE THREAD

**Issue by sasatte** [michikono/boxfit#7]
This is excellent! Exactly what I am looking for. However, is there angular only solution? If not, I will write one.

**Comment by michikono** [comment]
This plugin is for jquery so an angular plugin isn't really going to work. You'd need to redesign this from the ground up as a directive and avoiding a lot of the jquery code.

**Comment by sasatte** [comment]
Hi Michi,
Thanks. I did end up writing a angular only solution from scratch. In
addition, I need an approximate solution meaning I need to compute the font
size without DOM manipulation. Let me if see if I can clean it up and open
source it soon.

On Thu, Jun 5, 2014 at 11:30 AM, Michi Kono notifications@github.com
wrote:

> This plugin is for jquery so an angular plugin isn't really going to work.
> You'd need to redesign this from the ground up as a directive and avoiding
> a lot of the jquery code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/michikono/boxfit/issues/7#issuecomment-45183700.

## 

Sasatte Prashant Vishvanath
Founder
Interior Point Analytics

**Comment by michikono** [comment]
Good to hear, and good luck!
