### ISSUE TITLE
Add AMD/CJS support

### ISSUE THREAD

**Issue by JSteunou** [michikono/boxfit#8]
This plugin is missing AMD/CJS support and returning itself to avoid loading jquery + boxfit.

I could do a PR if you want.

**Comment by michikono** [comment]
I'm not super familiar with AMD, so a PR would be awesome! Please make sure to run `grunt build` before submitting! Thanks.

**Comment by JSteunou** [comment]
Done ;)

**Comment by michikono** [comment]
Merged in. Added to next revision. Closing.
